<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Enter fullscreen_plyr__poster</name>
   <tag></tag>
   <elementGuidId>ccddd571-d55f-44a2-ba6a-a066d82e4f98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tutorPlayer']/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.plyr__poster</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>de497374-f7de-4452-a953-f4df3da15a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>plyr__poster</value>
      <webElementGuid>f48a4894-770b-4d14-8e81-74ea95df2da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tutorPlayer&quot;)/div[@class=&quot;plyr__video-wrapper plyr__video-embed&quot;]/div[@class=&quot;plyr__poster&quot;]</value>
      <webElementGuid>c5639a24-05f6-4213-8c19-39b8e9590d90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tutorPlayer']/div[2]/div</value>
      <webElementGuid>74b4e865-d71b-425b-9d17-48619c7560be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/div[2]/div</value>
      <webElementGuid>b03b6e0b-c7ab-4f88-ac3f-f978af57f250</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
